[features]
seeds = false
skip-lint = false
[programs.devnet]
counter_program = "EcabWoR6LZA1VKK3WaW4rbJCG6RrKXKr17cm8ZgENEU3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/fer/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
